<?php

require_once dirname(__FILE__) . '/../FixedWidthIO.php';

/**
 * Test class for FixedWidthIO::array_formatfw.
 * Generated by PHPUnit on 2012-05-30 at 09:55:32.
 */
class FixedWidthIOArrray_formatfwTest extends PHPUnit_Framework_TestCase {

    /**
     * @var FixedWidthIO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FixedWidthIO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @expectedException FixedWidthIOIllegalParameterException
     * @dataProvider array_formatfwThrowsFixedWidthIOIllegalParameterExceptionProvider
     */
    public function testArray_formatfwThrowsFixedWidthIOIllegalParameterException(array $fields, array $fieldWidths, $truncateFields, $message) {
        FixedWidthIO::array_formatfw($fields, $fieldWidths, $truncateFields);
    }

    public function array_formatfwThrowsFixedWidthIOIllegalParameterExceptionProvider() {
        return array(
            array(array('abc'), array('1'), TRUE, 'Should only accept array of ints for $fieldWidths, array of strings supplied.'),
            array(array('abc'), array(-1), TRUE, 'Should only accept array of positive ints for $fieldWidths, negative value supplied.'),
            array(array('abc'), array(1), 'TRUE', 'Should only accept boolean for $truncateFields, string supplied'),
            array(array('abc'), array(1), '1', 'Should only accept boolean for $truncateFields, string supplied'),
            array(array('abc'), array(1), 1, 'Should only accept boolean for $truncateFields, int supplied'),
            array(array('abc'), array(1), 0, 'Should only accept boolean for $truncateFields, int supplied'),
        );
    }

    /**
     * @expectedException FixedWidthIOTooManyFieldsException
     * @dataProvider array_formatfwThrowsFixedWidthIOTooManyFieldsExceptionProvider
     */
    public function testArray_formatfwThrowsFixedWidthIOTooManyFieldsException(array $fields, array $fieldWidths) {
        FixedWidthIO::array_formatfw($fields, $fieldWidths);
    }

    public function array_formatfwThrowsFixedWidthIOTooManyFieldsExceptionProvider() {
        return array(
            array(array('a', 'b', 'c'), array(1, 1)),
            array(array('a'), array()),
            array(array('a', 'b', 'c'), array()),
            array(array('abc', 'def', 'xyd'), array(10, 10)),
        );
    }

    /**
     * @expectedException FixedWidthIOTooFewFieldsException
     * @dataProvider array_formatfwThrowsFixedWidthIOTooFewFieldsExceptionProvider
     */
    public function testArray_formatfwThrowsFixedWidthIOTooFewFieldsException(array $fields, array $fieldWidths) {
        FixedWidthIO::array_formatfw($fields, $fieldWidths);
    }

    public function array_formatfwThrowsFixedWidthIOTooFewFieldsExceptionProvider() {
        return array(
            array(array('a', 'b', 'c'), array(1, 1, 1, 1)),
            array(array(), array(1)),
            array(array(), array(1, 1, 1)),
            array(array('abcde', 'xyzhj'), array(5, 5, 0))
        );
    }

    /**
     * @expectedException FixedWidthIOFieldOverflowException
     * @dataProvider array_formatfwThrowsFixedWidthIOFieldOverflowExceptionProvider
     */
    public function testArray_formatfwThrowsFixedWidthIOFieldOverflowException(array $fields, array $fieldWidths) {
        FixedWidthIO::array_formatfw($fields, $fieldWidths);
    }

    public function array_formatfwThrowsFixedWidthIOFieldOverflowExceptionProvider() {
        return array(
            array(array('a'), array(0)),
            array(array('abcde'), array(4)),
            array(array('abcde'), array(1)),
            array(array('abc', 'abcd'), array(3, 3)),
        );
    }

    /**
     * @covers FixedWidthIO::array_formatfw
     * @dataProvider array_formatfwProvider
     */
    public function testArray_formatfw(array $fields, array $fieldWidths, $truncateFields, $expected) {
        $actual = FixedWidthIO::array_formatfw($fields, $fieldWidths, $truncateFields);
        $this->assertSame($expected, $actual);
    }

    public function array_formatfwProvider() {
        return array(
            array(array('abc'), array(3), FALSE, 'abc'),
            array(array('abc'), array(3), TRUE, 'abc'),
            array(array('a'), array(3), FALSE, 'a  '),
            array(array('a'), array(3), TRUE, 'a  '),
            array(array('abcd'), array(3), TRUE, 'abc'),
            array(array('Foo', 'Bob', 'Baz'), array(4, 4, 4), FALSE, "Foo Bob Baz "),
            array(array('Foo', 'Bob', 'Baz'), array(3, 3, 3), FALSE, "FooBobBaz"),
            array(array('1', '23', '45'), array(1, 2, 2), FALSE, "12345"),
            array(array('a'), array(1), FALSE, "a"),
            array(array('name' => 'Foo', 'number' => '10', 'street' => 'Test', 'test' => 'XYZ', 'code' => '1234'),
                array('name' => 6, 'number' => 6, 'street' => 20, 'test' => 5, 'code' => 4),
                FALSE,
                "Foo   10    Test                XYZ  1234"),
            array(array('Foo', 'Bob', 'Baz'), array(4, 4, 4), TRUE, "Foo Bob Baz "),
            array(array('Foo', 'Bob', 'Baz'), array(3, 3, 3), TRUE, "FooBobBaz"),
            array(array('Fooxyz', 'Bobxyz', 'Bazxyz'), array(3, 3, 3), TRUE, "FooBobBaz"),
            array(array('1', '23', '45'), array(1, 2, 2), TRUE, "12345"),
            array(array('a'), array(1), TRUE, "a"),
            array(array('name' => 'Foo', 'number' => '10', 'street' => 'Test', 'test' => 'XYZ', 'code' => '1234'),
                array('name' => 6, 'number' => 6, 'street' => 20, 'test' => 5, 'code' => 4),
                TRUE,
                "Foo   10    Test                XYZ  1234"),
        );
    }
    
}

?>
