<?php

require_once dirname(__FILE__) . '/../../IO/IOArrayIterator.php';

/**
 * Test class for IOArrayIterator.
 * Generated by PHPUnit on 2012-06-01 at 09:22:18.
 */
class IOArrayIteratorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IOArrayIterator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IOArrayIterator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers IOArrayIterator::initialize
     * @todo Implement testInitialize().
     */
    public function testInitialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IOArrayIterator::getException
     * @todo Implement testGetException().
     */
    public function testGetException() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IOArrayIterator::isHeaderMatch
     * @todo Implement testIsHeaderMatch().
     */
    public function testIsHeaderMatch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IOArrayIterator::current
     * @todo Implement testCurrent().
     */
    public function testCurrent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IOArrayIterator::key
     * @todo Implement testKey().
     */
    public function testKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IOArrayIterator::next
     * @todo Implement testNext().
     */
    public function testNext() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IOArrayIterator::rewind
     * @todo Implement testRewind().
     */
    public function testRewind() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IOArrayIterator::valid
     * @todo Implement testValid().
     */
    public function testValid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
