<?php
require_once dirname(__FILE__) . "/../../vendor/autoload.php";

/**
 * Test class for IOCSVFileWriter.
 * Generated by PHPUnit on 2012-06-01 at 09:43:39.
 */
class IOCSVFileWriterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IOCSVFileWriter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
//        $this->object = new IOCSVFileWriter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo implement tests for this class 
     */
    public function testMe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
