<?php

require_once dirname(__FILE__) . '/../../IO/IOCSVFileIterator.php';

/**
 * Test class for IOCSVFileIterator.
 * Generated by PHPUnit on 2012-06-01 at 11:39:50.
 */
class IOCSVFileIteratorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IOCSVFileIterator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
//        $this->object = new IOCSVFileIterator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testMe() {
        $this->markTestIncomplete();
    }
    
}

?>
