<?php

require_once dirname(__FILE__) . '/../../IO/IOCSVFileParser.php';

/**
 * Test class for IOCSVFileParser.
 * Generated by PHPUnit on 2012-06-01 at 09:18:30.
 */
class IOCSVFileParserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IOCSVFileParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
//        $this->object = new IOCSVFileParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers IOCSVFileparser::readLine
     * @todo Implement testReadLine().
     */
    public function testReadLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
