<?php

require_once dirname(__FILE__) . '/../../IO/IOFileWriter.php';

/**
 * Test class for IOFileWriter.
 * Generated by PHPUnit on 2012-06-01 at 09:43:39.
 */
class IOFileWriterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IOFileWriter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
//        $this->object = new IOFileWriter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers IOFileWriter::initialize
     * @todo Implement testInitialize().
     */
    public function testInitialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IOFileWriter::write
     * @todo Implement testWrite().
     */
    public function testWrite() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
