<?php
require_once dirname(__FILE__) . "/../../vendor/autoload.php";

/**
 * Test class for IOFixedWidthFileIterator.
 * Generated by PHPUnit on 2012-06-01 at 11:39:49.
 */
class IOFixedWidthFileIteratorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IOFixedWidthFileIterator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
//        $this->object = new IOFixedWidthFileIterator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    
    public function testMe() {
        $this->markTestIncomplete();
    }
    

}

?>
