<?php

require_once dirname(__FILE__) . '/../../IO/IOExceptions.php';

/**
 * Test class for IOFieldOverflowException.
 * Generated by PHPUnit on 2012-06-01 at 09:18:54.
 */
class IOFieldOverflowExceptionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IOFieldOverflowException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IOFieldOverflowException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
